site_name: MooQuant 量化框架
site_url: http://www.mooquant.com
site_description: Project documentation with Markdown.
site_author: BoPo <ibopo@126.com>
repo_url: https://github.com/bopo/mooquant/
theme: readthedocs

pages:
- 项目简述: index.md
- 用户指南:
    - 策略交易: tutorial/trading.md
    - 策略优化: tutorial/optimizing.md
    - 绘制图形: tutorial/plotting.md

- 代码说明:
  - 工具模块: develop/tools.md
  - 事件分析: develop/eventprofiler.md
  - TA-LIB 集成: develop/talib.md
  - 投资评估: develop/compinv.md
  - 策略范例: develop/samples.md

- 关于:
    - 更新日志: about/release.md
    - 授权许可: about/license.md

# copyright: Copyright &copy; 2017 <a href="https://twitter.com/_tomchristie">Tom Christie</a>, Maintained by the <a href="/about/release-notes/#maintenance-team">MkDocs Team</a>.

